name: world_trace
description: A cross-platform travel tracker for visited countries and goals (WorldTrace)
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.3
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.14
  path: ^1.8.3
  intl: ^0.20.2
  image_picker: ^1.1.2
  share_plus: ^12.0.1
  flutter_map: 8.2.2
  latlong2: ^0.9.0
  firebase_core: ^4.3.0
  # sign_in_with_apple: ^4.3.0  # RIMOSSO: plugin non piÃ¹ necessario per Android
  shared_preferences: ^2.1.1
  sign_in_button: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/geojson/world_simplified.geojson
